show_command_list = ["show clock",
                    "term monitor",
                    "term len 0",
                    "admin show platform",
                    "show version",
                    "show interfaces",
                    "show int des",
                    "show process cpu location 0/0/CPU0",
                    "show process cpu location 0/1/CPU0",
                    "show process cpu location 0/7/CPU0",
                    "show process cpu location 0/RSP0/CPU0",
                    "show process cpu location 0/RSP1/CPU0",
                    "sh watchdog memory-state location all",
                    "show run",
                    "show logging",
                    "show bundle",
                    "show ipv4 vrf all interface brief",
                    "show ipv4 vrf all interface bri | i Up",
                    'show interface | i "(line protocol| rate | Description)"',
                    'show interface | i "(line protocol| error| Description)"',
                    "show route",
                    "show route summary",
                    "show vrf all",
                    "show route vrf all",
                    "sh route vrf all summary",
                    "show bgp all all summary",
                    "show bgp vpnv4 unicast summary",
                    "show bgp neighbors",
                    "show bgp vpnv4 unicast neighbors detail",
                    "show bfd session",
                    "show bfd summary",
                    "show bfd",
                    "show arp vrf all",
                    "show arp",
                    "show cdp neighbor",
                    "show cdp neighbor detail",
                    "show interface summary",
                    "show route ipv4 isis",
                    "show isis interface brief",
                    "show isis adjacency",
                    "show isis adjacency-log",
                    "show isis topology",
                    "show isis database",
                    "show isis neighbors",
                    "show isis neighbors be31 detail",
                    "show isis neighbors be32 detail",
                    "show mpls mldp neighbor",
                    "show mpls mldp bindings",
                    "show mpls interfaces",
                    "show l2vpn xconnect",
                    "Show l2vpn xconnect detail",
                    "show clock",]
